# Inventory – Definiert auf welchen Rechnern das Playbook läuft
#
# "localhost" = der eigene Rechner
# "ansible_connection=local" = kein SSH nötig, arbeite direkt hier

[workstation]
localhost ansible_connection=local
